---
apiVersion: v1
kind: Service
metadata:
  name: boinc-client
  namespace: boinc
  labels:
    app: boinc-client
spec:
  ports:
    - port: 31416
      name: manager
      protocol: TCP
  selector:
    app: boinc-client
